# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

variables:
  # Change pip's cache directory to be inside the project directory since we can
  # only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PATH: "$PATH:/root/.local/bin"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip

stages:
  - build
  - test
  - deploy

build-package:
  stage: build
  script:
    - python --version  # For debugging
    # install from the zip file to see if files were forgotten
    - python setup.py sdist --dist-dir=dist --formats=zip
    - pip install --user --upgrade pip
    # download packages once and cache them for the others
    - pip install --user -r test-requirements.txt -r requirements.txt virtualenv wheel
  artifacts:
    paths:
      - sdist
    untracked: true

.run-tests:
  stage: test
  before_script:
    # install the package in a virtual env
    - pip install --user virtualenv
    - virtualenv ENV
    - source ENV/bin/activate
    # install package from build step
    - pip install dist/*.zip
    # test that the example works without the test dependencies
    - ./example.sh
    # install test requirements
    - pip install -r test-requirements.txt
  script:
    - test/test_code_quality.sh
    - pytest --x-wr-timezone=all

test-python-2.7:
  image: python:2.7
  extends:
  - .run-tests

test-python-3.7:
  image: python:3.7
  extends:
  - .run-tests

test-python-3.8:
  image: python:3.8
  extends:
  - .run-tests

test-python-3.9:
  image: python:3.9
  extends:
  - .run-tests

test-python-3.10:
  image: python:3.10
  extends:
  - .run-tests

deploy-package:
  stage: deploy
  before_script:
  - pip install --user wheel
  script:
    - python setup.py bdist_wheel sdist
  artifacts:
    paths:
      - dist/*
  rules:
    - if: '"$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH"'

